services:
  # --- INFRAESTRUCTURA COMÚN ---
  nats-server:
    image: nats:2.10-alpine
    container_name: nats-server
    networks:
      - gateway-app
    ports:
      - "4222:4222"
      - "8222:8222"

  # --- BASES DE DATOS INDEPENDIENTES ---
  # db-tickets:
  #   image: postgres:15-alpine
  #   container_name: db-tickets
  #   networks:
  #     - gateway-app
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: your_strong_password
  #     POSTGRES_DB: tickets_db
  #   volumes:
  #     - ./postgres_data_tickets:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"

  db-auth:
    image: postgres:15-alpine
    container_name: db-auth
    networks:
      - gateway-app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: your_strong_password
      POSTGRES_DB: auth_db
    volumes:
      - ./postgres_data_auth:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  # --- MICROSERVICIOS ---
  api-gateway:
    build:
      context: ./api-gateway
      target: development
    container_name: api-gateway
    networks:
      - gateway-app
    ports:
      - "3000:3000"
    environment:
      - NATS_URL=nats://nats-server:4222
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - nats-server

  auth-service:
    build:
      context: ./auth-service
      target: development
    container_name: auth-service
    networks:
      - gateway-app
    environment:
      - NATS_URL=nats://nats-server:4222
      - DATABASE_URL=postgresql://admin:your_strong_password@db-auth:5432/auth_db
      - JWT_SECRET=cambiame_en_produccion
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - nats-server
      - db-auth

  # tickets-service:
  #   build:
  #     context: ./tickets-service
  #     target: development
  #   container_name: tickets-service
  #   networks:
  #     - gateway-app
  #   environment:
  #     - NATS_URL=nats://nats-server:4222
  #     - DATABASE_URL=postgresql://admin:your_strong_password@db-tickets:5432/tickets_db
  #   volumes:
  #     - ./tickets-service:/app
  #     - /app/node_modules
  #   depends_on:
  #     - nats-server
  #     - db-tickets

  # --- FRONTEND ---
  # frontend-app:
  #   build:
  #     context: ./frontend-app
  #   container_name: frontend-app
  #   networks:
  #     - gateway-app
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./frontend-app:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:3000/api
  #   command: pnpm run dev

# --- CONFIGURACIÓN DE RED Y VOLÚMENES ---
networks:
  gateway-app:
    driver: bridge

volumes:
  postgres_data_tickets:
  postgres_data_auth: