services:
  # --- INFRAESTRUCTURA COMÚN ---
  nats-server:
    image: nats:2.10-alpine
    container_name: nats-server
    networks:
      - gateway-app
    restart: always
    command: ["-js", "-sd", "/data"]
    volumes:
      - /nats_data:/data

  # --- BASES DE DATOS INDEPENDIENTES ---

  db-auth:
    container_name: db-auth
    env_file: .env
    image: postgres:16.11-alpine3.23
    restart: always
    networks:
      - gateway-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
      DB_SPECIFIC_USER: ${APP_USER_AUTH}
      DB_SPECIFIC_PASSWORD: ${APP_USER_AUTH_PASSWORD}
      REPLICATION_USER: ${REPLICATION_USER}
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
    volumes:
      - /home/nexus-matrix/postgres_data_auth:/var/lib/postgresql/data
      - ./scripts/init.sh:/scripts/init.sh
    ports:
      - "127.0.0.1:5432:5432"
    command: >
      sh -c "
        docker-entrypoint.sh postgres &
        PID=$!;
        sh /scripts/init.sh;
        wait $$PID
      "

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  db-tickets:
    container_name: db-tickets
    env_file: .env
    image: postgres:16.11-alpine3.23
    restart: always
    networks:
      - gateway-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TICKETS}
      DB_SPECIFIC_USER: ${APP_USER_TICKETS}
      DB_SPECIFIC_PASSWORD: ${APP_USER_TICKETS_PASSWORD}
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
      REPLICATION_USER: ${REPLICATION_USER}
    volumes:
      - /home/nexus-matrix/postgres_data_tickets:/var/lib/postgresql/data
      - ./scripts/init.sh:/scripts/init.sh
    ports:
      - "127.0.0.1:5433:5432"
    command: >
      sh -c "
        docker-entrypoint.sh postgres &
        PID=$!;
        sh /scripts/init.sh;
        wait $$PID
      "

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  # --- MICROSERVICIOS ---
  api-gateway:
    env_file: .env
    container_name: api-gateway
    image: ghcr.io/gw-enterprise/app-launcher/api-gateway:latest
    networks:
      - gateway-app
    ports:
      - ${API_GATEWAY_PORT}:3000
    environment:
      NATS_SERVERS: ${NATS_SERVERS}
      APP_VERSION: ${APP_VERSION}
      PORT: ${API_GATEWAY_PORT}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    depends_on:
      nats-server:
        condition: service_started
    restart: always
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5

  tickets-service:
    env_file: .env
    container_name: tickets-service
    image: ghcr.io/gw-enterprise/app-launcher/tickets-service:latest
    networks:
      - gateway-app
    environment:
      NATS_SERVERS: ${NATS_SERVERS}
      APP_VERSION: ${APP_VERSION}
      PORT: ${TICKETS_SERVICE_PORT}
      DATABASE_URL: ${DATABASE_URL_TICKETS}
      TZ: America/Mexico_City
    depends_on:
      nats-server:
        condition: service_started
      db-tickets:
        condition: service_healthy
    restart: always
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    env_file: .env
    container_name: auth-service
    image: ghcr.io/gw-enterprise/app-launcher/auth-service:latest
    networks:
      - gateway-app
    environment:
      NATS_SERVERS: ${NATS_SERVERS}
      APP_VERSION: ${APP_VERSION}
      DATABASE_URL: ${DATABASE_URL_AUTH}
    depends_on:
      nats-server:
        condition: service_started
      db-auth:
        condition: service_healthy
    restart: always
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5

  notifications-service:
    env_file: .env
    container_name: notifications-service
    image: ghcr.io/gw-enterprise/app-launcher/notifications-service:latest
    networks:
      - gateway-app
    environment:
      NATS_SERVERS: ${NATS_SERVERS}
      APP_VERSION: ${APP_VERSION}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      MAIL_FROM: ${MAIL_FROM}
      IMAP_HOST: ${IMAP_HOST}
      IMAP_PORT: ${IMAP_PORT}
      IMAP_USER: ${IMAP_USER}
      IMAP_TENANT_ID: ${IMAP_TENANT_ID}
      IMAP_CLIENT_ID: ${IMAP_CLIENT_ID}
      IMAP_CLIENT_SECRET: ${IMAP_CLIENT_SECRET}
    depends_on:
      nats-server:
        condition: service_started
    restart: always
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5


  frontend-app:
    container_name: frontend-app
    image: ghcr.io/gw-enterprise/app-launcher/frontend-app:latest
    networks:
      - gateway-app
    ports:
      - "3001:80" 
    restart: always
    environment:
      - VITE_API_GATEWAY_URL=${VITE_API_GATEWAY_URL}

# --- CONFIGURACIÓN DE RED Y VOLÚMENES ---
networks:
  gateway-app:
    driver: bridge

volumes:
  nats_data:

name: gateway-app
