name: Deploy Nexus Matrix

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Orquestador
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.GH_PAT }}

      - name: Ejecutar comandos en IONOS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: admin2
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/vhosts/gatewayfabrication.com.mx/nexus.gatewayfabrication.com.mx


            pwd

            # Git pull y Docker
            git pull origin main
            docker-compose up -d --build
