name: Deploy Nexus Matrix

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Orquestador
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.GH_PAT }}

      - name: Ejecutar comandos en IONOS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: admin2
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 1. Entrar a la carpeta (Ruta directa)
            cd /var/www/vhosts/gatewayfabrication.com.mx/nexus.gatewayfabrication.com.mx

            # 2. Git (Sin sudo para evitar líos de llaves de root)
            git config --global --add safe.directory '*'
            git pull origin main
            git submodule update --init --recursive

            # 3. Docker (Aquí SI usamos sudo)
            sudo -n docker-compose -f compose.yaml -p nexus-matrix down || true
            sudo -n docker-compose -f compose.yaml -p nexus-matrix up -d --build

            # 4. Verificación
            sudo -n docker ps --filter "name=nexus-matrix"
